// export const ADD_NEW_NOTE = "ADD_NEW_NOTE";
// export const SET_USERNAME = "SET_USERNAME";
export const actions = {
  ADD_NEW_NOTE: "ADD_NEW_NOTE",
  SET_USERNAME: "SET_USERNAME",
  REMOVE_USERNAME: "REMOVE_USERNAME",
  ON_SEARCH_NOTE: "ON_SEARCH_NOTE",
  ON_DELETE_NOTE: "ON_DELETE_NOTE",
  ON_SET_CURRENT_EDIT_NOTE: "ON_SET_CURRENT_EDIT_NOTE",
  ON_HANDLE_MODAL: "ON_HANDLE_MODAL",
  ON_EDIT_NOTE: "ON_EDIT_NOTE",
};
